config/routes.rb
Rails.application.routes.draw do
  root 'blog_posts#index'
  devise_for :users
  # resources :users do
  #   member do
  #     get 'following'
  #   end
  # end
  get '/users/:id/following' => 'users#following', as: 'following'
  resources :blog_posts do
    resources :comments
    member do
      post 'like_or_unlike'
      get 'selected_user_profile'
      post 'follow'
      post 'unfollow'
    end
  end
  post '/signup' => 'users#signup'
  get '/my_blogs' => 'blog_posts#my_blogs'
  get '/home' => 'blog_posts#home'
  get '/profile' => 'users#profile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_many :comments, :dependent => :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter
  acts_as_follower
  acts_as_followable

  has_many :blog_posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected

  def authenticate_user
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :like_or_unlike, :selected_user_profile, :follow, :unfollow]

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def index
    @blog_posts = BlogPost.all
  end

  def my_blogs
    @my_blogs = current_user.blog_posts
  end

  def create
    @blog_post = BlogPost.new(blog_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_params)
        format.html { redirect_to @blog_post, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def home
  end

  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_or_unlike
    if current_user.voted_for? @blog_post
      @blog_post.unliked_by current_user
    else
      @blog_post.liked_by current_user
    end
  end

  def selected_user_profile
    @user = @blog_post.user
  end

  def follow
    @user = @blog_post.user
    current_user.follow(@user)
  end

  def unfollow
    @user = @blog_post.user
    current_user.stop_following(@user)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog_post).permit(:user_id, :title, :body)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = @blog_post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @blog_post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @blog_post.comments.new(comment_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to blog_post_path(@blog_post, @comment), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @blog_post.comments.find(params[:id])
    end

    def set_blog_post
      @blog_post = BlogPost.find(params[:blog_post_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :blog_post_id, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(blog_post) do |f| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, class: "wysiwyg" %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/_show_blog_post.html.erb
<div class="blog-card spring-fever blog_post_body">
  <div class="title-content">
    <div class="intro user-name"><%= link_to blog_post.user.email, selected_user_profile_blog_post_path %></div>
  </div><!-- /.title-content -->
  <div class="card-info body_blog">
    <div class="fr-view"><%= raw blog_post.body %></div>
  </div><!-- /.card-info -->
  <!-- overlays -->
  <div class="gradient-overlay"></div>
  <div class="color-overlay"></div>
</div><!-- /.blog-card -->

app/views/blog_posts/edit.html.erb
<%= render 'form', blog_post: @blog_post %>

app/views/blog_posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-login">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-12">
              <div class="wrapper" style="background: #efeff3;">
                <h1> Blogs</h1>
                <hr />
                <br />
                <% @blog_posts.each do |blog_post| %>
                  <div class="top">
                    <div class="content">
                      <div class="card first index-blog">
                        <a href="/blog_posts/<%= blog_post.id %>">
                          <p class="text">
                            <div class="fr-view"><%= raw blog_post.try(:body) %></div>
                          <br />
                          </p>
                          <p> By <%= blog_post.user.email %> </p>
                          <p class="date"><%= blog_post.created_at.strftime("%e %b, %Y") %></p>
                        </a>
                      </div>
                    </div>
                    <hr/>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blog_posts/list.html.erb
<%= link_to 'New Blog', new_blog_post_path %>
<div class="wrapper" style="background: #efeff3;">
  <% @blog_posts.each do |blog_post| %>
    <div class="top"><div class="title"><h1>My Blog</h1></div></div>
    <div class="content">
      <div class="card first">
        <p class="date"><%= blog_post.created_at.strftime("%e %b, %Y") %></p>
        <p class="text">
          <%= blog_post.body %>
        <br />
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/blog_posts/my_blogs.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-login">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-12">
              <div class="wrapper" style="background: #efeff3;">
                <% @my_blogs.each do |my_blog| %>
                  <div class="content">
                    <div class="card first index-blog">
                      <a href="/blog_posts/<%= my_blog.id %>">
                        <p class="text">
                          <div class="fr-view"><%= raw my_blog.try(:body) %></div>
                        <br />
                        </p>
                        <p> By <%= my_blog.user.email %> </p>
                        <p class="date"><%= my_blog.created_at.strftime("%e %b, %Y") %></p>
                      </a>
                    </div>
                    <%= link_to 'Edit Blog', edit_blog_post_path(my_blog) %> |
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blog_posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="panel panel-login">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-12">
            <%= render 'form', blog_post: @blog_post %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blog_posts/selected_user_profile.html.erb
<%# render 'users/user_profile' %>
<div class="container">
<div class="row">
<!-- code start -->
<div class="twPc-div">
  <a class="twPc-bg twPc-block"></a>
  <div>
    <div class="twPc-button">
      <!-- Twitter Button | you can get from: https://about.twitter.com/tr/resources/buttons#follow -->
      <% unless current_user.id == @user.id %>
        <% if current_user.following?(@user) %>
          <%= button_to 'Unfollow', unfollow_blog_post_path, method: :post, class: 'btn btn-danger' %>
        <% else %>
        <%= button_to 'Follow', follow_blog_post_path, method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
      <!-- Twitter Button -->
    </div>

    <div class="twPc-divUser">
      <div class="twPc-divName">
        <%= @user.try(:user_name) %>
      </div>
      <span>
        <%= @user.try(:email) %>
      </span>
    </div>
      <div class="twPc-divStats">
        <ul class="twPc-Arrange">
          <li class="twPc-ArrangeSizeFit">
            <a href=<%= "#{blog_posts_path}" %> title="blogs">
              <span class="twPc-StatLabel twPc-block">Blogs</span>
              <span class="twPc-StatValue"><%= @user.blog_posts.count %></span>
            </a>
          </li>
          <li class="twPc-ArrangeSizeFit">
            <a href="https://twitter.com/mertskaplan/following" title="885 Following">
              <span class="twPc-StatLabel twPc-block">Following</span>
              <span class="twPc-StatValue">885</span>
            </a>
          </li>
          <li class="twPc-ArrangeSizeFit">
            <a href="https://twitter.com/mertskaplan/followers" title="1.810 Followers">
              <span class="twPc-StatLabel twPc-block">Followers</span>
              <span class="twPc-StatValue">1.810</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
<!-- code end -->
</div>
</div>

app/views/blog_posts/show.html.erb
<%#= render :partial => post %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-login">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-12">
              <%= render 'show_blog_post', blog_post: @blog_post %>
              <div class="row">
                <div class="col-md-4">
                  <div class="like_unlike">
                    <% unless current_user.voted_for? @blog_post %>
                      <%= button_to 'Like', like_or_unlike_blog_post_path, method: :post, class: 'btn btn-primary' %>
                    <% else %>
                      <%= button_to 'Unlike', like_or_unlike_blog_post_path, method: :post, class: 'btn btn-danger' %>
                    <% end %>
                  <br/>
                  </div>
                </div>
                <% if current_user.id == @blog_post.user_id %>
                  <div class="col-md-8">
                    <%= link_to 'Edit Blog', edit_blog_post_path(@blog_post) %> | <%= link_to 'Delete', @blog_post, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </div>
                <% end %>
              </div>
              <br />
              <hr />
              <div class="row">
              <div class="col-xs-12">
                <p>Comments</p>
                <%= render 'comments/show', comments: @blog_post.comments.order(updated_at: :desc), blog_post: @blog_post %>
                <div class="row">
                  <div class="create-comment col-xs-12">
                    <%= form_for [@blog_post, Comment.new] do |f| %>
                      <div class="field">
                        <%= f.text_area :body, placeholder: 'Leave a comment', cols: "80", rows: "5" %>
                      </div>
                      <div class="field">
                        <%= f.hidden_field :blog_post_id %>
                      </div>

                      <div class="field">
                        <%= f.hidden_field :user_id %>
                      </div>

                      <button type="button" class="btn btn-primary"><%= f.submit "Add Comment"%></button>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', blog_posts_path %>

app/views/comments/_show.html.erb
<div class="comment-show">
  <% comments.each do |comment| %>
    <p>
      <%= comment.body %>
    </p>
    <% if current_user.id == comment.user_id %>
      <%= link_to 'Edit', edit_blog_post_comment_path(comment.blog_post, comment) %>
    <% end %>
    <hr />
  <% end %>
</div>

app/views/comments/new.html.erb
<%= link_to 'Back', blog_post_comment_path %>

app/views/layouts/_header.html.erb
<body class="index" id="page-top">
  <nav class="navbar navbar-default navbar-custom navbar-fixed-top" id="mainNav">
    <div class="container">
      <div class="navbar-header page-scroll">
        <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
          <span class="sr-only">Toggle navigation</span>
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand page-scroll" href="#page-top">Blog App</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% unless current_user %>
            <li>
              <a class="page-scroll" href="/users/sign_up">Sign Up</a>
            </li>
            <li>
              <a class="page-scroll" href="/users/sign_in">Sign In</a>
            </li>
          <% else %>
            <li>
              <a class="page-scroll" href=<%= "#{blog_posts_path}" %>>Blogs</a>
            </li>
            <li>
            <li>
              <a class="page-scroll" href=<%= "/my_blogs" %>>My Blogs</a>
            </li>
            <li>
              <a class="page-scroll" href=<%= "#{new_blog_post_path}" %>>Write</a>
            </li>
             <li>
              <a class="page-scroll" href=<%= "#{profile_path}" %>>Profile</a>
            </li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/users/_user_profile.html.erb
<div class="container">
<div class="row">
<!-- code start -->
<div class="twPc-div">
  <a class="twPc-bg twPc-block"></a>
  <div>
    <div class="twPc-button">
      <!-- Twitter Button | you can get from: https://about.twitter.com/tr/resources/buttons#follow -->
      <% unless current_user.id == @user.id %>
        <% if current_user.following?(@user) %>
          <%= button_to 'Unfollow', unfollow_blog_post_path, method: :post, class: 'btn btn-danger' %>
        <% else %>
        <%= button_to 'Follow', follow_blog_post_path, method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
      <!-- Twitter Button -->
    </div>

    <div class="twPc-divUser">
      <div class="twPc-divName">
        <%= @user.try(:user_name) %>
      </div>
      <span>
        <%= @user.try(:email) %>
      </span>
    </div>
      <div class="twPc-divStats">
        <ul class="twPc-Arrange">
          <li class="twPc-ArrangeSizeFit">
            <a href=<%= "#{blog_posts_path}" %> title="blogs">
              <span class="twPc-StatLabel twPc-block">Blogs</span>
              <span class="twPc-StatValue"><%= @user.blog_posts.count %></span>
            </a>
          </li>
          <li class="twPc-ArrangeSizeFit">
            <a href="#" title="885 Following">
              <span class="twPc-StatLabel twPc-block">Following</span>
              <span class="twPc-StatValue"><%= @user.follow_count %></span>
            </a>
          </li>
          <li class="twPc-ArrangeSizeFit">
            <a href="#" title="1.810 Followers">
              <span class="twPc-StatLabel twPc-block">Followers</span>
              <span class="twPc-StatValue"><%= @user.followers_count %></span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
<!-- code end -->
</div>
</div>

app/views/users/profile.html.erb
<%= render 'users/user_profile' %>